name: 'whisper_project'
description: 'Openai library Whisper Library from whisper.cpp for recognition audio to text / speech to text without heavy gpu, support server side and client side.'
version: '0.0.0'
repository: 'https://github.com/azkadev/whisper'
homepage: 'https://github.com/azkadev/general'
issue_tracker: 'https://github.com/azkadev/general/issues'
documentation: 'https://github.com/azkadev/whisper/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/azkadev'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '^3.2.3'
dependencies: 
  general_lib: '^0.0.42'
  mason_logger: '^0.2.11'
  packagex: '^0.0.58'
  path: '^1.9.0'
  universal_io: '^2.2.2'
  yaml: '^3.1.2'
  yaml_edit: '^2.2.0'
  yaml_writer: '^2.0.0'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
